name: Build (macOS)

on: [push, pull_request]

jobs:
  macOS:
    runs-on: macOS-latest
    needs: Init
    strategy:
      matrix:
        configuration: ["Debug", "Release"]
        include:
        - configuration: Debug
          build_param: --debug
          artifact_name: cellbox-macos-debug.zip
        - configuration: Release
          build_param:
          artifact_name: cellbox-macos-release.zip
    steps:
    - name: Clone Tree
      uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Install Dependencies
      run: |
        brew update
        brew unlink python@2
        brew install \
          pixman \
          sdl2 \
          libepoxy \
          coreutils \
          pkg-config \
          ccache
    - name: Initialize Compiler Cache
      id: cache
      uses: actions/cache@v1
      with:
        path: /tmp/cellbox-ccache
        key: cache-${{ runner.os }}-${{ matrix.configuration }}-${{ github.sha }}
        restore-keys: cache-${{ runner.os }}-${{ matrix.configuration }}-
    - name: Compile
      run: |
        export CCACHE_DIR=/tmp/cellbox-ccache
        export CCACHE_MAXSIZE=250M
        export PATH="/usr/local/opt/ccache/libexec:$PATH"
        ./build.sh ${{ env.BUILD_PARAM }}
        echo -e "\nCompiler Cache Stats:"
        ccache -s -c
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v1
      with:
        name: dist
        path: ${{ matrix.artifact_name }}
